### ISSUE TITLE
Page zoom

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/ProjectVisBug#127]
allow zooming really far out, and further in, than you currently can in the browser. allow zooming like you can do in any design tool.

**Comment by rehat101** [comment]
is this about wrapping the `main` with `pinch-zoom` and of course adding key controls?

**Comment by argyleink** [comment]
yep! i'm curious how much of the zoom in and out and pan behavior from a design tool we can mimic right here on any webpage

**Comment by argyleink** [comment]
maybe even v1 of this feature only does hotkey zooming like the following?
- Zoom In: `cmd + `
- Zoom Out: `cmd -` 
- Actual Size: `cmd + 0` 
- Center Canvas: `cmd + 1` 
- Zoom Selection: `cmd + 2`
- Center Selection: `cmd + 3`

**Comment by argyleink** [comment]
Tried a POC today that felt like it could totally be built upon to fulfill this feature:

```css
html {
    width: 500vw;
    height: 500vh;
    display: grid;
    place-content: center;
    overflow: scroll;
    background: hsl(0 0% 95%);
}
```

This plus listening for cmd+scroll events, we could transform scale the html tag. we get natural native scrolling and zooming. if it works out well, setup the keyboard events, call it good. Needs more QA, but wanted to share 👍
