### ISSUE TITLE
add a "debug" mode css

### ISSUE THREAD

**Issue by id0Sch** [GoogleChromeLabs/ProjectVisBug#233]
When debugging layout bugs i often use a snippet that puts the DOM in a debug mode that looks like that:
![image](https://user-images.githubusercontent.com/5864772/49085068-d424e900-f259-11e8-9ddb-e027b42918a1.png)

It basically shows each component with transparent borders to easily see the tree.
The css is pretty basic:
``` css
*:not(path):not(g) {
  color: hsla(210, 100%, 100%, 0.9) !important;
  background: hsla(210, 100%, 50%, 0.5) !important;
  outline: solid 0.25rem hsla(210, 100%, 100%, 0.5) !important;
  box-shadow: none !important;
}
```
and I even have a bookmarklet that does exactly that:
``` javascript
javascript:(()=>{var s= document.createElement('style');s.innerHTML='*:not(path):not(g) {color: hsla(210, 100%, 100%, 0.9) !important;background: hsla(210, 100%, 50%, 0.5) !important;outline: solid 0.25rem hsla(210, 100%, 100%, 0.5) !important;box-shadow: none !important;}';document.head.appendChild(s)})()
```

This could be a cool addition to the extension,
Thanks!!
